version: '2'

services:

  db:
    image: postgres
    container_name: banco_postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    # networks:
    #   - postgree-network  
  
  pgadmin4:
      image: dpage/pgadmin4
      container_name: pgadmin4
      restart: always
      # volumes:
      #   - ./:/var/www/captech
      environment: 
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=admin@admin
      ports: 
        - "15432:80"
      depends_on:
        - db
      # networks:
      #   - postgree-network 

  web:
    build: .
    # command: /bin/bash -c "composer install --ignore-platform-req && php artisan serve"
    container_name: captech_teste
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/captech
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    # environment:
    #   - POSTGRES_NAME=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    # depends_on:
    #   - db
    # networks:
    #   - postgree-network
    # working_dir: /var/www/captech
    
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - .:/var/www/captech
  #     - ./nginx/conf.d/:/etc/nginx/conf.d/
  #   depends_on:
  #     - web
  #     - db

# networks:
#   postgree-network: