# FROM ubuntu:20.04
FROM php:5.6-fpm


# Install unzip utility and libs needed by zip PHP extension 
RUN apt-get update && apt-get install -y \
    zlib1g-dev \
    libzip-dev \
    unzip
# sudo apt-get install zip php5.6-zip

# language
RUN apt-get install -y locales && locale-gen en_US.UTF-8
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'


# add repository
RUN apt-get install -y software-properties-common
RUN apt-get install -y gnupg2
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C2518248EEA14886
RUN LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php


# instalar o composer 2.2.18
RUN curl -O "https://getcomposer.org/download/2.2.18/composer.phar"
RUN chmod a+x composer.phar
RUN mv composer.phar /usr/local/bin/composer

# Set working directory on /var/www
WORKDIR /var/www/captech

# Copy repository files to /var/www/captech
COPY . /var/www/captech

# install nano and wget
RUN apt-get install -y nano wget

# upgrade and update 
RUN apt-get update && apt-get -y upgrade 
